name: Update README with latest download link
on:
  push:
    branches:
      - main
  schedule:
    - cron: "0 0 * * 0"

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4.1.6

      - name: Get latest release
        id: get_release
        uses: actions/github-script@v7.0.1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const response = await github.repos.listReleases({
              owner: 'tripleseven190504',
              repo: 'PYCDC BINARY',
            });
            const latestRelease = response.data[0];
            return latestRelease;

      - name: Update README
        run: |
          echo "\n ![][(https://readme-typing-svg.herokuapp.com?font=Rubik+Doodle+Shadow&amp;pause=1000&amp;color=6272A4&amp;center=true&amp;random=false&amp;width=435&amp;lines=D+o+w+n+l+o+a+d)](https://github.com/tripleseven190504/PYCDC/releases/tag/${{ steps.get_release.outputs.result }})" >> README.md
      - name: Commit changes
        run: |
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'actions@users.noreply.github.com'
          git add README.md
          git commit -m "Update README with latest download link"
          git push
