name: Update README with latest download link
on:
  push:
    branches:
      - main
  schedule:
    - cron: "0 0 * * 0"

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4.1.6

      - name: Update README
        run: |
          echo "# PYCDC-BINARY" > README.md
          echo "[![Download PYCDC](https://readme-typing-svg.herokuapp.com?font=Rubik+Doodle+Shadow&pause=1000&color=6272A4&center=true&random=false&width=435&lines=Download+PYCDC)](https://github.com/tripleseven190504/PYCDC-BINARY/releases/download/stable-release/pycdc.exe)" >> README.md
          echo "[![Download PYCDAS](https://readme-typing-svg.herokuapp.com?font=Rubik+Doodle+Shadow&pause=1000&color=6272A4&center=true&random=false&width=435&lines=Download+PYCDAS)](https://github.com/tripleseven190504/PYCDC-BINARY/releases/download/stable-release/pycdas.exe)" >> README.md

      - name: Commit changes
        run: |
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'actions@users.noreply.github.com'
          git add README.md
          git commit -m "Update README with latest download link"
          git push --force
