name: Build and Release Decompyle++
on:
  push:
    branches:
      - main
  schedule:
    - cron: "0 0 * * *"

jobs:
  build-job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.6

      - name: Get Commit Count
        run: |
          chmod +x .github/scripts/get-commit-count.sh
          STATUS=$(.github/scripts/get-commit-count.sh)
          echo $STATUS
          cat ./.github/commit-count
          if [ "$STATUS" == "True" ]; then
            git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
            git config --global user.name "github-actions[bot]"
            git add .
            NUMBER=$(cat ./.github/commit-count)
            git commit -m "Update current commit count #$NUMBER"
            git push --force
          else
            exit 0
          fi

      - name: Update system and install Mingw-w64
        run: |
          sudo apt update
          sudo apt install -y mingw-w64

      - name: Download PyInstaller Extractor
        run: |
          wget https://raw.githubusercontent.com/extremecoders-re/pyinstxtractor/master/pyinstxtractor.py
          chmod +x pyinstxtractor.py

      - name: Clone Decompyle++ repository
        run: git clone --depth=1 https://github.com/zrax/pycdc

      - name: Configure and build Decompyle++ with CMake
        run: >
          cd pycdc

          cmake -DCMAKE_SYSTEM_NAME=Windows
          -DCMAKE_C_COMPILER=i686-w64-mingw32-gcc
          -DCMAKE_CXX_COMPILER=i686-w64-mingw32-g++
          -DCMAKE_FIND_ROOT_PATH=/usr/i686-w64-mingw32
          -DCMAKE_FIND_ROOT_PATH_MODE_INCLUDE=ONLY
          -DCMAKE_FIND_ROOT_PATH_MODE_LIBRARY=ONLY
          -DCMAKE_FIND_ROOT_PATH_MODE_PROGRAM=NEVER
          -DCMAKE_CXX_STANDARD_LIBRARIES="-static-libgcc -static-libstdc++"
          .

          make

      - name: Release Decompyle++
        uses: ncipollo/release-action@v1
        with:
          name: Decompyle++
          tag: stable-release
          body: This release contains pre-built binaries for Windows from the original repository.
          artifacts: "pycdc/pycdc.exe,pycdc/pycdas.exe, pyinstxtractor.py"
          token: ${{ secrets.TOKEN }}
          allowUpdates: true
          makeLatest: true
