name: Compile pycdc for Windows
on:
  push:
    branches:
      - main
  schedule:
    - cron: "0 0 * * 0"

jobs:
  build-job:
    runs-on: ubuntu-22.04

    steps:
      - name: Install mingw-w64
        run: |
          sudo apt update
          sudo apt install -y mingw-w64

      - name: Clone pycdc
        run: git clone --depth=1 https://github.com/zrax/pycdc

      - name: Compile
        run: >
          cd pycdc

          echo "RELEASE_COMMIT=$(git log -1 --format=%h)" >> ${GITHUB_ENV}

          cmake -DCMAKE_SYSTEM_NAME=Windows
          -DCMAKE_C_COMPILER=i686-w64-mingw32-gcc
          -DCMAKE_CXX_COMPILER=i686-w64-mingw32-g++
          -DCMAKE_FIND_ROOT_PATH=/usr/i686-w64-mingw32
          -DCMAKE_FIND_ROOT_PATH_MODE_INCLUDE=ONLY
          -DCMAKE_FIND_ROOT_PATH_MODE_LIBRARY=ONLY
          -DCMAKE_FIND_ROOT_PATH_MODE_PROGRAM=NEVER
          -DCMAKE_CXX_STANDARD_LIBRARIES="-static-libgcc -static-libstdc++"
          .

          make

      - name: Create release Windows
        uses: ncipollo/release-action@v1
        with:
          name: Decompyle++
          tag: stable-release
          body: Decompyle++ binary for Windows
          artifacts: "pycdc/pycdc.exe,pycdc/pycdas.exe"
          token: ${{ secrets.TOKEN }}
          allowUpdates: true
          draft: true
